config:
  robot:
    config: "./robot_config_don_bot.yaml"
#    config: "./robot_config_kuka_arm.yaml"
    default_paramaters:
      collision_threshold_distance: {"value": 0.05, "step": 0.01, "min": 0, "max": 5}
      collision_check_distance: {"value": 0.1, "step": 0.01, "min": 0, "max": 5}
      samples: {"value": 20, "step": 1, "min": 3, "max": 50}
      duration: {"value": 10, "step": 1, "min": 3, "max": 50}
  solver: "./sqp_config.yaml"
  world:
    sdf: "/home/mahesh/MEGA/thesis/pycharm/trajPlanner/world_props/world/world.urdf"